### ISSUE TITLE
dashboard is empty in firefox but is normal in chrome

### ISSUE THREAD

**Issue by makingtime** [apache/skywalking-rocketbot-ui#133]
dashboard problems:
**1, it is empty in firefox but is normal in chrome.**
**2, it dosen't adjust to screen size in firefox but it is normal in chrome**

in Firefox
![image](https://user-images.githubusercontent.com/53243647/62989035-125e4900-be79-11e9-99b0-ee09b81b3c59.png)

in Chrome
![image](https://user-images.githubusercontent.com/53243647/62989154-81d43880-be79-11e9-93af-a787e90abb59.png)

the UI version I'm using is 6.3.0,

I'm using docker-compose to setup a test env, this is my docker-compose.yml,

```
version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      TZ: Asia/Shanghai
    networks: 
      - docker-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
  oap:
    image: apache/skywalking-oap-server:6.3.0
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    networks: 
      - docker-net
    ports:
      - 11800:11800
      - 12800:12800
      - 1234:1234
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro
  ui:
    image: apache/skywalking-ui:6.3.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    networks: 
      - docker-net
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro

networks:
  docker-net:
    driver: bridge

```
